[package]
name = "alphabet_icon"
version = "0.1.0"
authors = ["faizaan.m <faizaan.m@endurance.com>"]

[dependencies]
rocket = "=0.3.16"
rocket_codegen = "=0.3.16"
svg = "=0.5.6"
simplesvg = "0.4.0"
cached = "=0.4.1"
lazy_static = "=0.2.8"
cache_2q = "=0.8.4"
rocket_cors = "=0.2.0"